# Generated by Django 3.2.7 on 2022-01-23 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('round', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('playdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('height', models.BigIntegerField(blank=True, null=True)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.teams')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['last_name', 'first_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SiteUsage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('action_types', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.users')),
            ],
            options={
                'db_table': 'site_usage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scores', models.BigIntegerField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.games')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.users')),
            ],
            options={
                'db_table': 'scores',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='games',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_1', to='dashboard.teams'),
        ),
        migrations.AddField(
            model_name='games',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_2', to='dashboard.teams'),
        ),
    ]
