# Generated by Django 3.2.7 on 2022-01-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220124_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteusage',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
